#common config
spring:
  profiles:
    active: prod
  application:
    name: video
  #file max size and request max size
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
#port
server:
  port: 8088
  servlet:
    context-path: /api

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml

#pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

file:
  prefix: /file
  pattern: /file/**